version: "3.9"

services:
  database:
    image: postgres
    container_name: database_ignite
    restart: always
    ports: 
      - 5432:5432 # Porta padrão do postgres
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: rentalx
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229 # Porta para debug
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local